sudo: enabled
language: r
warnings_are_errors: true

# Use Xenial whenever running in Linux (ignored for OS X)
dist: xenial

# Disable lintr-bot comments by default
env:
  - LINTR_COMMENT_BOT=false
  - RGL_USE_NULL=TRUE

# Construct the matrix of OS and R versions
os:
  - linux
  - osx
r:
  - release
  - devel

# Specify any additional packages that might be needed
addons:
  homebrew:
    packages:
    - llvm

before_install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      mkdir -p ~/.R
      # Ensure that R will use clang from homebrew llvm (which includes openmp support)
      echo "CC=$(brew --prefix llvm)/bin/clang" > ~/.R/Makevars
      echo "CXX=$(brew --prefix llvm)/bin/clang++" >> ~/.R/Makevars
      echo "LDFLAGS=-L$(brew --prefix llvm)/lib" >> ~/.R/Makevars
    fi

# Explicitly enable the lintr-bot for one build (this avoids duplicate comments).
# Travis treats builds with different environment variables as different builds.
# We therefore remove the one we don't want in order to replace it with the one
# we do.
matrix:
  exclude:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=false
    - os: osx
      r: devel
      env: LINTR_COMMENT_BOT=false
  include:
    - os: linux
      r: release
      env: LINTR_COMMENT_BOT=true

# Add R packages from CRAN. If newer versions are needed, r_github_packages
# can be used instead
r_packages:
  - covr
  - lintr

after_success:
  - Rscript -e 'covr::codecov()'
  